config/routes.rb
Rails.application.routes.draw do
  
  get 'import/importcsv'
  
  get 'import/action'
  post 'import/action'

  get 'callapi/getaccessuser'
  post 'callapi/getaccessuser'
  
  root 'aouthsetup#setup'
  
  get 'aouthsetup/callback'
  post 'aouthsetup/callback'

  get 'aouthsetup/getcode'
  post 'aouthsetup/getcode'

  get 'aouthsetup/setup'
  
  
  resources 'import', only: :importcsv do
    collection { post :importcsv }
  end
  
  
  

end

app/models/importuser.rb
require 'csv'

class Importuser < ActiveRecord::Base
  
  # CSVファイルの内容をDBに登録する
  #def self.import(file)

  #  imported_num = 0

  #  # 文字コード変換のためにKernel#openとCSV#newを併用。
  #  # 参考: http://qiita.com/labocho/items/8559576b71642b79df67
  #  open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
  #    csv = CSV.new(f, :headers => :first_row)
  #    csv.each do |row|
  #      next if row.header_row?

  #      # CSVの行情報をHASHに変換
  #      table = Hash[[row.headers, row.fields].transpose]
  #
  #      # 登録済みユーザー情報取得。
  #      # 登録されてなければ作成
  #      user = find_by(:id => table["id"])
  #      if user.nil?
  #        user = new
  #      end

  #      # ユーザー情報更新
  #      user.attributes = table.to_hash.slice(
  #                          *table.to_hash.except(:id, :created_at, :updated_at).keys)

  #      # バリデーションOKの場合は保存
  #      if user.valid?
  #        user.save!
  #        imported_num += 1
  #      end
  #    end
  #  end

  #  # 更新件数を返却
  #  imported_num
  #end
  
  def self.import(file)
    
    list=[]
    CSV.foreach(file.path, headers: true) do |row|
      #obj = new
      #obj.attributes = row.to_hash.slice(*updatable_attributes)
      #obj.save!
      #username = row.to_hash["ユーザー名"]
      #userno = row.to_hash["社員番号"]
      #item = username + "-" + userno
      list.push(row.to_hash)
    end
    return list
  end

  #def self.updatable_attributes
  #  ["name","status","content"]
  #end
  
end

app/controllers/aouthsetup_controller.rb
class AouthsetupController < ApplicationController
  
require 'http'
CTX = OpenSSL::SSL::SSLContext.new
CTX.verify_mode = OpenSSL::SSL::VERIFY_NONE
  
  #トップページ（入力画面）
  def setup
  end
  
  #入力値の受取り画面
  def getcode
    
    #Veiwから値を受取る
    @@key = 	params[:email].presence
    @@client =	params[:clientId].presence
    @@secret =	params[:clientSecret].presence
    @@deviceId =	params[:deviceId].presence
    #@@callbackuri = 'https://import-user-yumikotsunai.c9users.io/aouthsetup/callback'
    @@callbackuri = 'https://importusers.herokuapp.com/aouthsetup/callback'
    
    #connectのoauth認証のためのURLにアクセスする  (A)リソースオーナーにAuthorization Request送信
    req = 'https://connect.lockstate.jp/oauth/'+'authorize?'+'client_id='+@@client+'&response_type=code&redirect_uri='+@@callbackuri
    
    redirect_to req
    
  end
  
  #認証コードの受取りとトークンの発行
  def callback
    
    #(B)リソースオーナーからAuthorization Grant受取り
    code = params[:code]
    
    #(C)認可サーバーにAuthorization Grant送信
    postform = {'code' => code \
    ,'client_id' => @@client \
    ,'client_secret' => @@secret \
    ,'redirect_uri' => @@callbackuri\
    ,'grant_type' => 'authorization_code' }
    
    res = HTTP.headers("Content-Type" => "application/x-www-form-urlencoded")
    .post("https://connect.lockstate.jp/oauth/token", :ssl_context => CTX , :form => postform)

    #(D)認可サーバーからレスポンス（アクセストークン）受取り
    #認証失敗の場合
    if res.code!=200
      @error = res
      @state = "認証に失敗しました"
      render
    #認証成功の場合
    else
      @error = res
      @state = "認証に成功しました"
      json = ActiveSupport::JSON.decode( res.body )
      puts(json)
      
      #アクセストークン
      @@accessToken = json["access_token"]
      puts(@@accessToken)
      render
    end
  end
  
  #アクセストークンを返す
  def getAccessToken
    return @@accessToken
  end
  
  #デバイスIDを返す
  def getDeviceId
    return @@deviceId
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callapi_controller.rb
class CallapiController < ApplicationController
  
require 'http'
require 'csv'
CTX = OpenSSL::SSL::SSLContext.new
CTX.verify_mode = OpenSSL::SSL::VERIFY_NONE

  #アクセスユーザーの作成
  def getaccessuser
    
    #AouthsetupControllerクラスからアクセストークンを取得
    aouthctr = AouthsetupController.new
    accessToken = aouthctr.getAccessToken
    
    #ImportControllerクラスからインポートデータを取得
    importctr = ImportController.new
    items = importctr.getItems
    
    @successList = []
    @errorList = []
    for user in items
    
      puts("アクセスユーザー作成")
      name = user["ユーザー名"]
      pin = user["社員番号"]
      
      postbody1 = {
        "type": "access_user",
        "attributes": {
          "name": name,
          "pin": pin,
        }
      }
      authtoken = "Bearer "+ accessToken
      res1 = HTTP.headers("Content-Type" => "application/json",:Authorization => authtoken )
      .post("https://api.lockstate.jp/access_persons", :ssl_context => CTX , :body => postbody1.to_json)
      
      if res1.code == 201
        j = ActiveSupport::JSON.decode(res1.body)
        data = j["data"]
        userId = data["id"]
        
        puts("アクセスゲストにロック権限を追加")
        deviceId = aouthctr.getDeviceId
        
        postbody2 = {
          "attributes": {
            "accessible_id": deviceId,
            "accessible_type": "lock",
          }
        }
        authtoken = "Bearer "+ accessToken
        apiUri = "https://api.lockstate.jp/access_persons/" + userId + "/accesses"
        
        res2 = HTTP.headers("Content-Type" => "application/json",:Authorization => authtoken)
        .post(apiUri, :ssl_context => CTX , :body => postbody2.to_json)
        
      end
      
      if res1.code == 201 and res2.code == 201
        @successList.push(name + "," + pin)
      else
        @errorList.push(name + "," + pin)
      end
      
    end
    
  end
  
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  
  #インポート画面の表示
  def importcsv
  end
  
  #CSVファイルのインポート
  def action
    
    if params[:csv_file].blank?
      redirect_to("/import/importcsv", alert: 'インポートするCSVファイルを選択してください')
    else
      extension = params[:csv_file].path.slice(-3,3)
      if(extension != "csv")
        redirect_to("/import/importcsv", alert: 'インポートするCSVファイルを選択してください')
      else
        @@items = Importuser.import(params[:csv_file])
      end
      
      #for userinfo in @@items
      #  username = userinfo["ユーザー名"]
      #  userno = userinfo["社員番号"]
      #end
    end
  end
  
  #アクセストークンを返す
  def getItems
    return @@items
  end
  
end

app/helpers/aouthsetup_helper.rb
module AouthsetupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callapi_helper.rb
module CallapiHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/views/aouthsetup/callback.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
    <h2>ConnectAPIの認証結果</h2>
    <p><%= @state  %></p>
    <!--CSVインポートボタンを表示-->
    <%= form_tag import_importcsv_path do %>
      <input type="submit" value="CSVインポート" class="btn primary-btn">
    <%end%>
</div>

app/views/aouthsetup/getcode.html.erb
<h1>Aouthsetup#getcode</h1>
<p>Find me in app/views/aouthsetup/getcode.html.erb</p>

app/views/aouthsetup/setup.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
  <h2>ConnectシステムのAPI認証を行います</h2>
  <p>以下に、LockState Connectの情報を入力してください</p>
</div>

<div style= "text-align:center;line-height:100%;padding:50px;">
  <!--getcode.htmlに送信-->
  <%= form_tag aouthsetup_getcode_path do %>
  
    <p>アカウントメールアドレス</p>
    <input type="text" class="form-control title-field" name="email" style="width:500px" value="demo@remotelock.com">
    <p>クライアントID</p>
    <!--<input type="text" class="form-control title-field" name="clientId" style="width:500px" value="a4b24a461019d48457c7ad108b7e53c9c499cb43206da51936e9dc240f68e45e">-->
    <input type="text" class="form-control title-field" name="clientId" style="width:500px" value="fd90f0372330839027d9cdc0a409c47913384f75692fc5787eb050fba29ceea9">
    <p>シークレット</p>
    <!--<input type="text" class="form-control title-field" name="clientSecret" style="width:500px" value="668d261cd6c279440cc74aded86ce40c643ef1b1b16608f8782cc213832bdc31">-->
    <input type="text" class="form-control title-field" name="clientSecret" style="width:500px" value="5cc3e1d20426eb2f84251facdec69f7d53ee9c88986f2a236e82c98fbcb4afac">
    <p>デバイスID</p>
    <input type="text" class="form-control title-field" name="deviceId" style="width:500px" value="09ca0c78-b289-408a-95e1-202de97be912">
    
    
    <input type="submit" value="送信" class="btn primary-btn">
  
  <%end%>
</div>

app/views/callapi/getaccessuser.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
  <h4>以下のユーザーは正しく登録されました</h4>
    <% @successList.each do |success| %>
    <%= success %><br>
  <% end %>
  <h4>以下のユーザーは正しく登録されませんでした</h4>
    <% @errorList.each do |error| %>
    <%= error %><br>
  <% end %>
</div>

app/views/import/action.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
    <!--アクセスゲスト登録ボタンを表示-->
    <%= form_tag callapi_getaccessuser_path do %>
      <input type="submit" value="アクセスゲスト登録" class="btn primary-btn">
    <%end%>
</div>

app/views/import/importcsv.html.erb
<div style= "text-align:center;line-height:100%;padding:10px;">
  <%= form_tag({controller: "import", action: "action", method: "post"}, {multipart: true}) do %>
    <%= file_field_tag :csv_file %>
    <%= submit_tag "CSVファイル読込み" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>